<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Nairdwood Launcher</AssemblyName>
    <RootNamespace>Nairdwood.Launcher</RootNamespace>
    <ApplicationIcon>Assets\nairdwood.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\nairdwood-text.png" />
  </ItemGroup>
</Project>
